add post form
n-krasnikov/news-frontend pull request #4
Opened 2023-07-19 14:25 UTC by n-krasnikov

2023-07-21 07:02 UTC, ekaterinagaltsova approved these changes

2023-07-21 08:54 UTC, skaptelinin requested changes

2023-07-21 08:54 UTC, skaptelinin commented on src/api/postPost.ts
> +export const postPost = async (payload: IPostCreate) => {
Здесь лучше подойдет createPost

2023-07-21 08:54 UTC, skaptelinin commented on src/components/BaseModal/BaseModal.tsx
> +          {modalType?.includes(SIGN) && <AuthForm modalType={modalType ?? ''} />}
Эта модалка умеет слишком много всего. Нет ничего страшного в том, чтобы немного покопипастить код. В дальнейшем для авторизации и создания поста может понадобиться куча своих уникальных пропсов, потому лучше так не делать. **В текущей архитектуре поменять это будет сложно, потому оставь как есть.**

2023-07-21 08:54 UTC, skaptelinin commented on src/components/Header/Header.css
>    margin: 0 5px;
На будущее - в чистом CSS в этом случае лучше использовать БЭМ. У тебя будет блок button, на который вешаются стили, и он же будет элементом относительно блока .header. На элемент как раз будут навешаны марджины и прочее позиционирование. **Ты БЭМ не используешь, потому менять уже ничего не надо**

2023-07-21 08:54 UTC, skaptelinin commented on src/components/Header/Header.tsx
> +import defaultImage from '../../assets/react.svg';
Обычно стили импортируются в самом конце

2023-07-21 08:54 UTC, skaptelinin commented on src/components/Header/Header.tsx
>    const buttons = [SIGN_IN, SIGN_UP];
По факту это константа. Ее можно вынести за пределы компонента.

2023-07-21 08:54 UTC, skaptelinin commented on src/components/Header/Header.tsx
>    const openModal = (type: string) => {
Здесь лучше использовать union или enum. Так тебе не нужно будет хранить константы с состояниями.

2023-07-21 08:54 UTC, skaptelinin commented on src/components/Header/Header.tsx
> +    dispatch(logout());
Токен стоит удалять в саге, если она есть. У тебя может быть много разных мест, откуда можно разлогиниться, потому для этого процесса должен быть единый источник истины.

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.css
> +  margin: 10px 0 0 0;
Старайся избегать такого. У компонента не должно быть внешних отсупов, головная боль с позиционированием должна ложиться на родителей.

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +  fields,
константы должны быть в UPPER_SNAKE_CASE

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +  const [image, setImage] = useState<File | null>(null);
image не используется в рендере, потому его лучше заменить на ref. Ты можешь повесить ref на инпут с картинкой, и в самбите тупо доставать файл из рефа.

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +  const submitForm = (values: Values) => {
тип Values не говорит ровным счетом ни о чем. Постарайся придумать название, которое лучше определяет, что сокрыто внутри)

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +                    severity={SEVERITY_ERROR}
Я бы не стал выносить это в константу. Если ты напрямую строку передашь, это будет проще читаться

2023-07-21 08:54 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +                    message={errors[name as keyof object] as string}
Проще наверное будет сказать, что у errors тип `Record<string, string>`. Тогда мы можем написать так
```
(errors as Record<string, string>)[name]
```

2023-07-21 08:54 UTC, skaptelinin commented on src/helpers/sortPosts.ts
> +  posts.sort((a, b) => {
метод sort мутирует исходный массив. В ECMA2023 есть метод toSorted, который возвращает новый массив. Если у тебя бабель не поддерживает ECMA2023, то здесь лучше создавать копию массива и сортировать его.

2023-07-21 08:54 UTC, skaptelinin commented on src/locales.json
> +  "AVATAR_ALT": "Falied to load avatar :("
Локали на стажерском проекте это круто! Но у тебя часть бизнес-логики завязана на локали и их сравнения. Так лучше не делать, потому что они могут меняться неконтролируемым образом. Плюс если добавить другой язык, то у тебя сравнения вообще перестанут работать.

2023-07-21 08:54 UTC, skaptelinin commented on src/pages/UserPage/UserPage.tsx
> +  if (error && error instanceof Object) return <ErrorPage status={error?.status} message={error?.data?.detail}/>;
Тут скорее всего подразумевается ошибка запроса. В axios есть метод isAxiosError, и есть тип AxiosError. Так будет проще с типизацией.

2023-07-21 08:54 UTC, skaptelinin commented on src/redux/actions/posts.ts
> +import { IPost, IPostCreate } from "../../vite-env";
Кавычки должны быть единообразные. Либо везде одинарные, либо везде двойные.

2023-07-21 08:54 UTC, skaptelinin commented on src/redux/sagas/postCreateSaga.ts
> +      yield put(postCreateFailed((error as AxiosError)?.response?.data?.detail  ?? ''));
Перед `??` 2 пробела)

2023-07-21 08:54 UTC, skaptelinin commented on src/redux/sagas/postCreateSaga.ts
> +function* onCreatePost({payload}: IPostCreateAction) {
просто createPost. Префикс `on` обычно означает, что функция делигирует обработку события куда-то дальше.

2023-07-21 15:32 UTC, skaptelinin requested changes

2023-07-21 15:32 UTC, skaptelinin commented on src/components/BaseModal/BaseModal.css
> +  color: '#FCEFD4';
на будущее -  в CSS кавычки не нужны для значений

2023-07-21 15:32 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +      ? imageRef.current?.files[0]
Если у нас есть длина массива файлов, то чейнить уже не нужно.

2023-07-21 15:32 UTC, skaptelinin commented on src/components/PostForm/constants.ts
> +
titleField, textField и tagsField - костанты. Для констант мы используем UPPER_SNAKE_CASE :)

2023-07-21 15:32 UTC, skaptelinin commented on src/components/PostForm/constants.ts
> +export const FORM_VALIDATION = object().shape({
FORM_VALIDATION потенциально сложный объект с каким-то поведением, не уверен что его можно считать константой. Обычно константы это нечто простое и захардкоженное.

2023-07-21 15:32 UTC, skaptelinin commented on src/components/Header/constants.ts
> +
Здесь все еще остается проблема с неконтролируемыми значениями.

2023-07-21 15:32 UTC, skaptelinin commented on src/helpers/sortPosts.ts
> +  const currentPosts = {...posts};
currentPosts это массив. Лучше сделай явный spread массива
```
const currentPosts = [...posts];
```

2023-07-21 15:32 UTC, skaptelinin commented on src/pages/UserPage/UserPage.tsx
> +  if (error && error instanceof Object) return <ErrorPage status={error?.status} message={error?.data?.detail}/>;
UPD. Это даже AxiosResponse.

2023-07-21 15:32 UTC, skaptelinin commented on src/vite-env.d.ts
> +  modalType?: 'Sign In' | 'Sign Up' | 'Add Post' | 'Edit Profile'
лучше сделать так:
```
type ModalType = 'signIn' | 'signUp' | 'addPost' | 'editProfile';

modalType?: ModalType
```
И дальше все функции, которые принимают в себя modalType, можно типизировать через ModalType. В итоге тайпскрипт будет гарантировать, что ты не вызовешь эту функцию с некорректным значением. Плюс не нужно будет смешивать значения из локалей с состоянием модалки.

2023-07-24 09:41 UTC, skaptelinin requested changes

2023-07-24 09:41 UTC, skaptelinin commented on src/components/AuthForm/AuthForm.tsx
> +    password: passwordValidation
При SignIn лучше не делать валидацию пароля. Она может меняться со временем, и пользователи со старыми паролями просто не смогут залогиниться.

2023-07-24 09:41 UTC, skaptelinin commented on src/components/PostForm/PostForm.tsx
> +                {touched[name as keyof object] && errors[name as keyof object] &&
У тебя здесь тайпскрипту не нравится типизация FORM_FIELDS. Ты можешь написать такой интерфейс:
```
interface FieldsConfig {
  as: 'input' | 'textarea'
  name: string
  placeholder: string
  rows: string
}
```
Тогда тайпскрипт поймет, что в name лежит string, и тебе не придется делать никаких преобразований типов. Вот ссылка на документацию формика, там есть типы touched и errors
https://formik.org/docs/api/formik#touched--field-string-boolean-

2023-07-24 13:11 UTC, skaptelinin approved these changes

2023-07-24 13:11 UTC, skaptelinin commented on src/components/BaseModal/BaseModal.tsx
> +          {modalType === ADD_POST && <PostForm />}
Благодаря типизации можно не хранить значения в константах. Если ты попытаешься сравнить modalType с какой-нибудь рандомной строкой, то тайпскрипт ошибку кинет.

2023-07-24 13:15 UTC, merged