edit profile
n-krasnikov/news-frontend pull request #5
Opened 2023-07-25 11:27 UTC by n-krasnikov

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/api/editUser.ts
> +export const editUser = async (id:string, payload: IEditUser) => {
потерялся пробел

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +import { userEditRequested } from '../../redux/actions/user';
непорядочный импорт

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +
лишняя пустая строка

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +
ы

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +  const usernameValidation = string()
может хотя бы вынести выше компонента?

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +    ? avatarRef.current?.files[0]
avatarRef.current.files[0]

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/EditUserForm.tsx
> +      <Typography variant='h5' className='form-title'>{ modalType }</Typography>
JSX

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/EditUserForm/constants.ts
> +}
![Снимок экрана 2023-07-25 в 15 36 07](https://github.com/n-krasnikov/news-frontend/assets/63230140/ff88a997-36a4-46d1-86ee-2e684167ba4f)
дублирует?

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/components/UserCard/constants.ts
> +export
просто export?

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.ts
> +  USER_EDIT_FAILED,
есть кейс?

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/redux/sagas/editUserSaga.ts
> +function* editProfile({payload}: IEditUserAction) {
укрась пробелами

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/redux/sagas/editUserSaga.ts
> +
призрак строки?

2023-07-25 12:42 UTC, ekaterinagaltsova commented on src/redux/sagas/editUserSaga.ts
> +    const id = userData?.id;
const { userData: { id } } = yield select((state: RootState) => state.auth);
не?

2023-07-26 08:26 UTC, skaptelinin requested changes

2023-07-26 08:26 UTC, skaptelinin commented on src/components/EditUserForm/EditUserForm.css
Пустые файлы лучше в проект не добавлять

2023-07-26 08:26 UTC, skaptelinin commented on src/components/EditUserForm/EditUserForm.tsx
> +        {({errors, touched}) =>(
пробел нужно после  => добавить

2023-07-26 08:26 UTC, skaptelinin commented on src/components/UserCard/UserCard.tsx
> +            <Button onClick={()=> openModal(EDIT_PROFILE as ModalType)}>{EDIT_PROFILE}</Button>
Константам можно тип указать, и не нужно будет преобразования делать

2023-07-26 08:26 UTC, skaptelinin commented on src/redux/actions/user.ts
> +export const userFailed = (error: object) => ({
На будущее - тип object лучше не использовать. Он почти никак не помогает нам в разработке

2023-07-26 08:26 UTC, skaptelinin commented on src/redux/sagas/editUserSaga.ts
> +      yield put(userEditFailed((error as AxiosError)?.response?.data?.detail ?? ''));
Я вовремя не заметил, что у тебя почти все саги написаны в таком стиле. Сейчас это уже поздно править, но на будущее - независимо от того, что именно упало, тебе нужно показать ошибку пользователю. Вся раззница в том, что при ошибке бэка ты получаешь сообщение и статус, а на фронте это будет что-то типа undefined is not a function

2023-07-26 08:58 UTC, skaptelinin approved these changes

2023-07-26 13:01 UTC, merged